The ``7-base_geometry.py``
==============================

using ``7-base_geometry.py``
--------------------------------

Importing the function frm the module:
       >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
       >>> bg = BaseGeometry()

Using
===============

testing simple:
       >>> bg.integer_validator("width", 89)


test using age less than 0:
       >>> bg.integer_validator("age", 0)
       Traceback (most recent call last):
        ...
       ValueError: age must be greater than 0

test using no argments:
       >>> bg.integer_validator()
       Traceback (most recent call last):
        ...
       TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

test messing one arg:
       >>> bg.integer_validator("no")
       Traceback (most recent call last):
        ...
       TypeError: integer_validator() missing 1 required positional argument: 'value'

test using string value:
       >>> bg.integer_validator("Me", "4")
       Traceback (most recent call last):
        ...
       TypeError: Me must be an integer

using differnet value:
       >>> bg.integer_validator("abs", None)
       Traceback (most recent call last):
       ...
       TypeError: abs must be an integer

       >>> bg.integer_validator("as", True)
       Traceback (most recent call last):
       ...
       TypeError: as must be an integer

       >>> bg.integer_validator("ab", [6])
       Traceback (most recent call last):
        ...
       TypeError: ab must be an integer

       >>> bg.integer_validator("mm", (8,))
       Traceback (most recent call last):
        ...
       TypeError: mm must be an integer

test using list in value:
       >>> bg.integer_validator("Me", {3, 2})
       Traceback (most recent call last):
        ...
       TypeError: Me must be an integer

test using negative number:
       >>> bg.integer_validator("distance", -4)
       Traceback (most recent call last):
        ...
       ValueError: distance must be greater than 0
